# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180312_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref_number',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
