# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_ref_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_big',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_big',
        ),
        migrations.AddField(
            model_name='product',
            name='name_common',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
