# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 18:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180314_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_1',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_2',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_3',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_description_1',
            field=models.CharField(blank=True, default='Sposób użycia', max_length=64, null=True),
        ),
    ]
