# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-18 18:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180318_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_description',
            field=models.CharField(blank=True, default='Opis', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_description_2',
            field=models.CharField(blank=True, default='Składniki aktywne', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_description_3',
            field=models.CharField(blank=True, default='Zużycie', max_length=64, null=True),
        ),
    ]
