# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productaddfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_3',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
